# Generated by Django 5.1.7 on 2025-03-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitaire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
